SystemOrganization addCategory: #'DynaCASE-PetriNets'!
SystemOrganization addCategory: 'DynaCASE-PetriNets-Adapters'!
SystemOrganization addCategory: 'DynaCASE-PetriNets-Controllers'!
SystemOrganization addCategory: 'DynaCASE-PetriNets-Examples'!
SystemOrganization addCategory: 'DynaCASE-PetriNets-Models'!
SystemOrganization addCategory: 'DynaCASE-PetriNets-Shapes'!
SystemOrganization addCategory: 'DynaCASE-PetriNets-Simulation'!
SystemOrganization addCategory: 'DynaCASE-PetriNets-Tests'!
