private - contents
inhibitorArcIconContents
	"Private - Method generated with the content of the file File @ C:\Users\Ruiner\Pharo\images\DC-2015-07-15-roassal\icons\inhibitorArc.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B
AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAA1SURBVDhPYxgF9Af/kTDJAF0TSYbg
UgwWBxHEYGwAlzgGoNgAEEBXTJJmGABpguFRAAYMDACr7hjoX3/kFQAAAABJRU5ErkJggg=='