private - contents
inhibitorArcIconContents
	"Private - Method generated with the content of the file File @ C:\Users\Ruiner\Pharo\images\DC-2015-07-14\icons\inhibitorArc.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAAXNSR0IArs4c6QAAAARnQU1B
AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABQSURBVDhPzZJBCgAgCAS1///ZhBWR
KM2bc0lih62IRYQ6LFu/GSjUl2ZmDEgWgqY9gDkTYhrojtW9uAjdhuyVNB2PAD9rAO4gWQsH
474G0QbYxTAKr1OVVwAAAABJRU5ErkJggg=='