private - contents
petriNetIconContents
	"Private - Method generated with the content of the file File @ C:\Users\Ruiner\Pharo\images\DC-2015-07-15-roassal\icons\petriNet.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B
AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABNSURBVDhP3Y9RCgAgDEJ3/0sXBoNh
NlhBQQ/8SNSRES2oDJfKI+8HAEqubY7K4IPr97+AEitjynFBDbgns8rMFBlvaRLuLQdYGSFn
1gGjuDbKYn//LwAAAABJRU5ErkJggg=='