private - contents
petriNetIconContents
	"Private - Method generated with the content of the file File @ C:\Users\Ruiner\Pharo\images\DC-2015-07-14\icons\petriNet.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAAXNSR0IArs4c6QAAAARnQU1B
AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABlSURBVDhPpZFRDsAgCEPH7n/njq2m
I0SJbO9H1BYEDcDxYGYMdDJlGFwdnYXnHOs2bUO7h7cCdbXa+dFDPRzxtQLTq++C3f8SOeXU
Eyd+R6siemcUZAODRBTkKfmd4JbnotkDcAHIg1P1ogAwEAAAAABJRU5ErkJggg=='