private - contents
placeWithTokenIconContents
	"Private - Method generated with the content of the file File @ C:\Users\Ruiner\Pharo\images\DC-2015-07-15-roassal\icons\placeWithToken.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B
AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABfSURBVDhPnY1RDsAwCEK9/6W70MRl
awVpX+KP8jAIg4yFCsoS9wvNOXKyZU/k5HVuZGAV4NbdaSDlnIq5V8fvVMw9OwIlg7ZA8fNu
SjbnpKTMYumUtDkWaMWVFIQY8QCOuTfJOVht4wAAAABJRU5ErkJggg=='