private - contents
placeIconContents
	"Private - Method generated with the content of the file File @ C:\Users\Ruiner\Pharo\images\DC-2015-07-15-roassal\icons\place.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B
AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABNSURBVDhP5Y1BCgAgCAT9/6cLA4Oy
tdWODXiJmU0ADRxFJIYj7C/QY2LDuZnYmE0lVp4HlNF+PLB0lRHXZEaOrj4yI1cPCddwx4Ig
FOlXnyvVPkOOFgAAAABJRU5ErkJggg=='