private - contents
placeIconContents
	"Private - Method generated with the content of the file File @ C:\Users\Ruiner\Pharo\images\DC-2015-07-14\icons\place.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAAXNSR0IArs4c6QAAAARnQU1B
AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABrSURBVDhPzZHBAoAgCEPB//9ngma6
sIxj7yRsIKKamRCq2k8X2cCxu5PspGQP0Hh1A1bbmQne3A5LUfA4ScINuKdV3Mxu9BXvPt9Q
5FcFWE8b+yoSN1RqxvbnSJsalm6/BuEjwwHgflkVOQBVUEUMfqeMhgAAAABJRU5ErkJggg=='