private - contents
placeWithTokenIconContents
	"Private - Method generated with the content of the file File @ C:\Users\Ruiner\Pharo\images\DC-2015-07-14\icons\placeWithToken.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B
AACxjwv8YQUAAAAJcEhZcwAADsIAAA7CARUoSoAAAACGSURBVDhPlZPbDsAgCEPB///nzRJZ
tAPU82AWbcslmT4dIVR1fK0EUvkFwBwJQfT2BXjVzOywrtk52JkBayygajsCWu+k3ZqZZQQG
4V6J8S7SgNmYhYCygxPSgHkv1Y7QW3+/XyLGgq/hqGbcYSPchnh1sOzgJIQ14c8E6Dq/5wCH
K8UykRff7VQJOIQnBgAAAABJRU5ErkJggg=='