private - contents
resetArcIconContents
	"Private - Method generated with the content of the file File @ C:\Users\Ruiner\Pharo\images\DC-2015-07-15-roassal\icons\resetArc.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B
AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAA+SURBVDhPYxgFtAX/oTQywCaGE4AU
wzAMYBPDCZAVwzRgE8MQJBXjBNgUYhPDCbApxCaGE2BTRJTGkQUYGAC/Ny/RNQKItgAAAABJ
RU5ErkJggg=='