private - contents
resetArcIconContents
	"Private - Method generated with the content of the file File @ C:\Users\Ruiner\Pharo\images\DC-2015-07-14\icons\resetArc.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAAXNSR0IArs4c6QAAAARnQU1B
AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABNSURBVDhPY/z//z8DKYAJShMNhoYG
RkZGKAsM0LjYbQAqQlaHzMXnJGQ9QIDGJRZgiThkk4CyaFx8TkIzC8LFrgEoh6wamTv00xID
AwDN4yEZaNcgdgAAAABJRU5ErkJggg=='