Class {
	#name : 'OPPetriNetsIcons',
	#superclass : 'OPIcons',
	#category : 'OpenPonk-PetriNets-Adapters',
	#package : 'OpenPonk-PetriNets',
	#tag : 'Adapters'
}

{ #category : 'accessing - icons' }
OPPetriNetsIcons class >> arcIcon [

	^ Form fromBinaryStream: self arcIconContents base64Decoded asByteArray readStream
]

{ #category : 'private - contents' }
OPPetriNetsIcons class >> arcIconContents [
	"Private - Method generated with the content of the file File @ C:\Users\Ruiner\Pharo\images\DC-2015-07-15-roassal\icons\arc.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B
AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAApSURBVDhPYxgF9Af/oTRFAGQI1QwC
A5iJ5GKyAdmaKbKZIicPT8DAAADJtBfpwGY0agAAAABJRU5ErkJggg=='
]

{ #category : 'accessing - icons' }
OPPetriNetsIcons class >> inhibitorArcIcon [

	^ Form fromBinaryStream: self inhibitorArcIconContents base64Decoded asByteArray readStream
]

{ #category : 'private - contents' }
OPPetriNetsIcons class >> inhibitorArcIconContents [
	"Private - Method generated with the content of the file File @ C:\Users\Ruiner\Pharo\images\DC-2015-07-15-roassal\icons\inhibitorArc.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B
AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAA1SURBVDhPYxgF9Af/kTDJAF0TSYbg
UgwWBxHEYGwAlzgGoNgAEEBXTJJmGABpguFRAAYMDACr7hjoX3/kFQAAAABJRU5ErkJggg=='
]

{ #category : 'accessing - icons' }
OPPetriNetsIcons class >> petriNetIcon [

	^ Form fromBinaryStream: self petriNetIconContents base64Decoded asByteArray readStream
]

{ #category : 'private - contents' }
OPPetriNetsIcons class >> petriNetIconContents [
	"Private - Method generated with the content of the file File @ C:\Users\Ruiner\Pharo\images\DC-2015-07-15-roassal\icons\petriNet.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B
AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABNSURBVDhP3Y9RCgAgDEJ3/0sXBoNh
NlhBQQ/8SNSRES2oDJfKI+8HAEqubY7K4IPr97+AEitjynFBDbgns8rMFBlvaRLuLQdYGSFn
1gGjuDbKYn//LwAAAABJRU5ErkJggg=='
]

{ #category : 'accessing - icons' }
OPPetriNetsIcons class >> placeIcon [

	^ Form fromBinaryStream: self placeIconContents base64Decoded asByteArray readStream
]

{ #category : 'private - contents' }
OPPetriNetsIcons class >> placeIconContents [
	"Private - Method generated with the content of the file File @ C:\Users\Ruiner\Pharo\images\DC-2015-07-15-roassal\icons\place.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B
AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABNSURBVDhP5Y1BCgAgCAT9/6cLA4Oy
tdWODXiJmU0ADRxFJIYj7C/QY2LDuZnYmE0lVp4HlNF+PLB0lRHXZEaOrj4yI1cPCddwx4Ig
FOlXnyvVPkOOFgAAAABJRU5ErkJggg=='
]

{ #category : 'accessing - icons' }
OPPetriNetsIcons class >> placeWithTokenIcon [

	^ Form fromBinaryStream: self placeWithTokenIconContents base64Decoded asByteArray readStream
]

{ #category : 'private - contents' }
OPPetriNetsIcons class >> placeWithTokenIconContents [
	"Private - Method generated with the content of the file File @ C:\Users\Ruiner\Pharo\images\DC-2015-07-15-roassal\icons\placeWithToken.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B
AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABfSURBVDhPnY1RDsAwCEK9/6W70MRl
awVpX+KP8jAIg4yFCsoS9wvNOXKyZU/k5HVuZGAV4NbdaSDlnIq5V8fvVMw9OwIlg7ZA8fNu
SjbnpKTMYumUtDkWaMWVFIQY8QCOuTfJOVht4wAAAABJRU5ErkJggg=='
]

{ #category : 'accessing - icons' }
OPPetriNetsIcons class >> resetArcIcon [

	^ Form fromBinaryStream: self resetArcIconContents base64Decoded asByteArray readStream
]

{ #category : 'private - contents' }
OPPetriNetsIcons class >> resetArcIconContents [
	"Private - Method generated with the content of the file File @ C:\Users\Ruiner\Pharo\images\DC-2015-07-15-roassal\icons\resetArc.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B
AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAA+SURBVDhPYxgFtAX/oTQywCaGE4AU
wzAMYBPDCZAVwzRgE8MQJBXjBNgUYhPDCbApxCaGE2BTRJTGkQUYGAC/Ny/RNQKItgAAAABJ
RU5ErkJggg=='
]

{ #category : 'accessing - icons' }
OPPetriNetsIcons class >> transitionIcon [

	^ Form fromBinaryStream: self transitionIconContents base64Decoded asByteArray readStream
]

{ #category : 'private - contents' }
OPPetriNetsIcons class >> transitionIconContents [
	"Private - Method generated with the content of the file File @ C:\Users\Ruiner\Pharo\images\DC-2015-07-15-roassal\icons\transition.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B
AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAiSURBVDhPY6AW+E8mhgMUDpFg1IBR
A0BgOBpADqYUMDAAAPLWM83NmmJrAAAAAElFTkSuQmCC'
]
