Class {
	#name : 'OPBCPetriNetToken',
	#superclass : 'Object',
	#category : 'OpenPonk-BooleanColoredPetriNets-Models',
	#package : 'OpenPonk-BooleanColoredPetriNets',
	#tag : 'Models'
}

{ #category : 'testing' }
OPBCPetriNetToken >> isFalse [
	^ false
]

{ #category : 'testing' }
OPBCPetriNetToken >> isNoToken [
	^ false
]

{ #category : 'testing' }
OPBCPetriNetToken >> isTrue [
	^ false
]
