SystemOrganization addCategory: #'OpenPonk-PetriNets'!
SystemOrganization addCategory: 'OpenPonk-PetriNets-Adapters'!
SystemOrganization addCategory: 'OpenPonk-PetriNets-Controllers'!
SystemOrganization addCategory: 'OpenPonk-PetriNets-Examples'!
SystemOrganization addCategory: 'OpenPonk-PetriNets-Models'!
SystemOrganization addCategory: 'OpenPonk-PetriNets-Shapes'!
SystemOrganization addCategory: 'OpenPonk-PetriNets-Simulation'!
SystemOrganization addCategory: 'OpenPonk-PetriNets-Tests'!
SystemOrganization addCategory: 'OpenPonk-PetriNets-Tests'!
Tests'!
